### PR TITLE
Linting and CI

### PR DESCRIPTION
**Pull request by jchristgit**
Adds continuous integration with Travis to validate code using `pylint` on branches and in PRs.

### CODE REVIEW

**Comment by robstolarz** [comment]
* Needs some squashing. Commits like f63b435 and 18b1342 should be squashed. Basically anything that isn't a big idea ("Validate python files with PEP8", "Add linter PEP8 test", and so on) should be squashed. 

* Commits with titles >50 chars should be shortened, with end punctuation removed (I'm looking at you, 9768efd and c50b3e1). If you need more room to explain, use the first line as a title and lines 3+ as a description body, wrapped to 80 chars or whatever the kernel standard is.

Make your changes with `git rebase -i <your first commit>~1`, whether by using the `edit` or `squash` commands. Then `git push -f` back on to this branch.

Thanks.

**Review by robstolarz — CHANGES_REQUESTED** [review]
* Needs some squashing. Commits like f63b435 and 18b1342 should be squashed. Basically anything that isn't a big idea ("Validate python files with PEP8", "Add linter PEP8 test", and so on) should be squashed. 

* Commits with titles >50 chars should be shortened, with end punctuation removed (I'm looking at you, 9768efd and c50b3e1). If you need more room to explain, use the first line as a title and lines 3+ as a description body, wrapped to 80 chars or whatever the kernel standard is.

Make your changes with `git rebase -i <your first commit>~1`, whether by using the `edit` or `squash` commands. Then `git push -f` back on to this branch.

Thanks.

**Review by aeshthetic — COMMENTED** [review]
Tested and succeeded? Appears to be ready to merge, but should be tested if not done already. (Knowing you I doubt you'd try to merge without testing).

**Comment by jchristgit** [comment]
@aeshthetic the tests basically just tested themselves for linter warnings.

**Review by robstolarz — CHANGES_REQUESTED** [review]
* 468f148, ccd540d, 1514212, ab1aef0 have commit titles that are too long. Please keep them to 50 chars or less, and use the body of the commit for further description. 

For example, ccd540d could be formatted like: 
```
Rewrite tests

* Use pylint instead of pycodestyle
* Capture pylint outputs
* Show pylint outputs in the error message.
```

* Squash 3d5db9f and 4610666. They're just formatting commits, so they should be squashed down.

Thanks for the stellar code. I'm sure these little changes shouldn't be too much of a hassle.

**Review by robstolarz — APPROVED** [review]

**Pull request merged**
